import { useEffect } from 'react';
import type { NextPage } from "next";
import MyComponent from './MyComponent';
import Head from "next/head";
import Image from "next/image";
import InfoButton from './InfoButton';
import Footer from './Footer'; // Import the Footer component
import styles from '../styles/Home.module.css';
import faqStyles from './FAQ.module.css';
import React from 'react';
import Link from 'next/link';
import Header from "./header"; // Correct for default export

const Home: NextPage = () => {
  useEffect(() => {
    const handleResize = () => {
      const logoStrip = document.querySelector(`.${styles['logo-strip']}`);
      if (logoStrip) {
        logoStrip.style.animation = 'none';
        setTimeout(() => {
          logoStrip.style.animation = '';
        }, 10); // A short delay to trigger the animation reset
      }
    };

    window.addEventListener('resize', handleResize);
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  const toggleFAQ = (faqNumber: number) => {
    const faqAnswer = document.getElementById(`faq${faqNumber}`);
    const arrow = document.getElementById(`arrow${faqNumber}`);
    if (faqAnswer?.style.display === 'none' || faqAnswer?.style.display === '') {
      faqAnswer.style.display = 'block';
      arrow?.classList.add('rotate');
    } else {
      faqAnswer.style.display = 'none';
      arrow?.classList.remove('rotate');
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>AIL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles['cui-banner']}>
        APPROVED FOR IL4 - CONTROLLED UNCLASSIFIED INFORMATION (CUI)
      </div>

       <div className={styles.divider}></div>

 <div>
  <Header /> {/* Floating header */}
  <div className={styles.header}>
    {/* All other page content goes here */}
  </div>
</div>
      <div className={styles.divider}></div>

      <main className={styles.main}>
         <h1 className={styles.title}>
         Revolutionizing Naval Operations with AI-Driven Tech Data Integration
        </h1>

        <MyComponent /> {/* Adding MyComponent here */}

        <div className={styles.grid}>
          <Link href="/dod-deliverables" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>
              Access ingested documentation. Search technical data corpus to
              validate, verify, and review the latest resources.
            </p>
          </Link>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>
              Embark on your journey to master AIL with engaging and interactive
              courses tailored to your operational needs.
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>
              Discover and explore how to utilize AIL effectively to meet your
              specific needs comprehensively.
            </p>
          </a>

          <a
            href="https://docs.replit.com/category/deployments"
            className={styles.card}
          >
            <h2>Start &rarr;</h2>
            <p>
              Search a corpus of technical data with AI support to make better
              data-driven decisions.
            </p>
          </a>
        </div>

        <hr className={styles.customDivider} />
        <div> <h4>Powered by</h4></div>

        {/* Logo Strip */}
        <div className={styles['logo-container']}>
          <div className={styles['logo-strip']}>
            <img src="/logo1.png" alt="Logo 1" />
            <img src="/logo2.png" alt="Logo 2" />
            <img src="/logo4.png" alt="Logo 4" />
            <img src="/logo5.png" alt="Logo 5" />
            {/* Add more logos as needed */}
          </div>
        </div>

        <h2 className={styles['alt-title']}>Frequently asked questions</h2> {/* Add FAQ title here */}

        {/* FAQ Section */}
        <div className={faqStyles.faqContainer}>
          <div className={faqStyles.faq}>
            <button className={faqStyles.faqQuestion} onClick={() => toggleFAQ(1)}>
              What is AI Librarian?
              <span className={faqStyles.arrow} id="arrow1">&#9660;</span> {/* Down arrow */}
            </button>
            <div className={faqStyles.faqAnswer} id="faq1">
              <p>Empower the Department of the Navy with cutting-edge AI solutions that streamline technical documentation, enhance decision-making, and ensure mission readiness. </p><p> Our advanced integration platform transforms complex data into actionable insights, enabling seamless collaboration and operational excellence. </p>
              <div className="gif-container">
                <img src="/testlaunch.gif" alt="Test Launch AI Gen GIF"/>
                <h5>— AI Generated GIF of Test Missile Launch</h5>
              </div>
            </div>
          </div>

          <div className={faqStyles.faq}>
            <button className={faqStyles.faqQuestion} onClick={() => toggleFAQ(2)}>
              How does AI Librarian work?
              <span className={faqStyles.arrow} id="arrow2">&#9660;</span> {/* Down arrow */}
            </button>
            <div className={faqStyles.faqAnswer} id="faq2">
              <p>The AI Librarian is a cutting-edge tool that combines advanced language models, semantic understanding, and generative AI to interpret complex queries and deliver precise, context-aware responses. 
                
                </p><p> It assists with tasks like summarizing documents, organizing data, and providing actionable guidance.  </p>Equipped with parametric capabilities and a modular, package-based architecture, it ensures seamless integration, scalability, and adaptability, making it a powerful asset for managing technical data and enhancing productivity.<p>  </p>
            </div>
          </div>

          <div className={faqStyles.faq}>
            <button className={faqStyles.faqQuestion} onClick={() => toggleFAQ(3)}>
              Is my data safe with AI Librarian?
              <span className={faqStyles.arrow} id="arrow3">&#9660;</span> {/* Down arrow */}
            </button>
            <div className={faqStyles.faqAnswer} id="faq3">
              <p>The U.S. Government Information System (USG IS) prioritizes security over personal privacy.  </p><p>While robust measures like authentication and access controls protect data, all communications and stored information are routinely monitored, searched, and can be seized for authorized purposes.</p><p>Privacy is not guaranteed.</p>
            </div>
          </div><p> CONTROLLED BY: NSWC PHD </p><p> CUI CATEGORY: Controlled Technical Information (CTI) </p><p> DISTRIBUTION / DISSEMINATION CONTROL:DISTRIBUTION STATEMENT C: DISTRIBUTION AUTHORIZED TO U.S.
          GOVERNMENT AGENCIES AND THEIR CONTRACTORS; ADMINISTRATIVE/ OPERATIONAL USE; DD MMM YYYY. OTHER
          REQUESTS FOR THIS WEB CLIENT SHALL BE REFERRED TO THE NAVAL SEA SYSTEMS COMMAND (PEO IWS 1.0).
          WARNING: THIS WEB CLIENT CONTAINS TECHNICAL DATA WHOSE EXPORT IS RESTRICTED BY THE ARMS EXPORT
          CONTROL ACT (TITLE 22, U.S.C., SEC. 2751 ET. SEQ.) OR THE EXPORT ADMINISTRATION ACT OF 1979(TITLE 50, U.S.C., APP
          2401 ET SEQ.), AS AMENDED. VIOLATIONS OF THESE EXPORT LAWS ARE SUBJECT TO SEVERE CRIMINAL PENALTIES.
          DISSEMINATE IN ACCORDANCE WITH PROVISIONS OF DOD DIRECTIVE 5230.25. </p><p>
          DESTRUCTION NOTICE:  FOR UNCLASSIFIED, LIMITED
          DOCUMENTS, DESTROY BY ANY METHOD THAT WILL PREVENT DISCLOSURE OF CONTENTS OR RECONSTRUCTION OF
          THE DOCUMENTS.
          POINT OF CONTACT: NAVAL SEA SYSTEMS COMMAND PROGRAM EXECUTIVE OFFICE FOR INTEGRATED WARFARE
          SYSTEMS, 1CT. 1333 ISAAC HULL AVE WASHINGTON NAVY YARD, DC 20376.</p><p>
          
          
          PUBLISHED UNDER AUTHORITY OF THE NAVAL SEA SYSTEMS COMMAND</p>
        </div>
      </main>

      <InfoButton /> {/* Add the InfoButton here */}
      <Footer /> {/* Add Footer component here */}
    </div>
  );
};

export default Home;
